### ISSUE TITLE
English language strings are not hosted in AMOS

### ISSUE THREAD

**Issue by germanvaleroelizondo** [rschrenk/moodle-mod_confman#11]
Hi,

I wanted to translate into Spanish your mod_confman plugin, but it is not hosted in AMOS at https://lang.moodle.org/ .

This is usually caused by a coding error.

Can you please have a look at the developer's documentation at https://docs.moodle.org/dev/Plugin_contribution_checklist#Strings ?

Thanks in advance

**Comment by rschrenk** [comment]
Thank you for your message. I think I found the issue. Please try again.

Kind regards!

**Comment by germanvaleroelizondo** [comment]
Yes indeed.

That was extremely quick and efficient.

Congratulations.

I will translate yout plugin right away :)

THANKS A LOT
