### ISSUE TITLE
Suboptimal input param type

### ISSUE THREAD

**Issue by mudrd8mz** [rschrenk/moodle-mod_confman#6]
it seems some input params have been declared as `PARAM_TEXT` - such as action in ajax.php. That does not seems to be appropriate - TEXT is generally for longer texts such as forum posts.

These look more like a PARAM_ALPHANUMEXT. Please refer to inline documentation for details and always pick the most specific / limiting type possible.

**Comment by mudrd8mz** [comment]
Worse than that
```
$filename = required_param("filename", PARAM_TEXT);
```

**Comment by rschrenk** [comment]
Plugin is now using PARAM_ALPHANUMEXT and PARAM_FILE is applicable.
