### ISSUE TITLE
Why are you hiding errors everywhere with the @-sign?

### ISSUE THREAD

**Issue by mudrd8mz** [rschrenk/moodle-mod_confman#9]
Why all those `@` signs in the code like this?
```
        $c = @json_decode($this->data->contents);
        $this->data->targetgroups = @$c->targetgroups;
        $this->data->description = @$c->description;
        $this->data->types = @$c->types;
        $this->data->organization = @$c->organization;
        $this->data->title_pre = @$c->title_pre;
        $this->data->title_post = @$c->title_post;
        $this->data->memo = @$c->memo;
```

**Comment by rschrenk** [comment]
In case the object from the database is outdated and misses certain fields (e.g. additional fields were added), or the whole object is invalid / not yet created, I can assure that all necessary fields of the current version are set at least with an empty string.

But as this style is not common I wrote it in another way.
